# This is a basic workflow that is manually triggered

name: Test Automation

on:
  workflow_dispatch:
    branches: [master]
    inputs:
      test_type:
        description: 'Please input test type.'
        type: choice
        required: true
        default: 'e2e'
        options:
          - e2e
          - integration
      test_environment:
        description: 'Please input environment to test.'
        type: choice
        required: true
        default: 'SIT'
        options:
          - SIT
          - UAT
      githost_environment:
        description: 'Please input git host environment to run the test (use legacy when vpn is required).'
        type: choice
        required: true
        default: 'ubuntu-22-4core'
        options:
          - ubuntu-22-4core
          - legacy
      squad:
        description: 'Please input squad. Example: spvcockpit, are, agenttools, dms, ndf4w, ndf2w, operation, sharia, etc'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FormatingStandart:
    name: Lint and Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Depedencies
        run: npm i
      - name: Lint and Prettier check
        run: |
          npm run lint
          npm run format
          npm run format:fix
